#!/bin/sh

set -e

./script/setup

echo "==> Updating all the things..."
echo "  > Pulling master for all vim submodules..."
git submodule foreach git pull origin master &> /dev/null

git status -s -b
